name: ChurchPlanting
favicon: null
layout_spectrum: 0.00241
typography_spectrum: 0.6836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4fcf1'
    - '#88dff3'
    - '#242e32'
    - '#eb657a'
    - '#62746c'
  brandStrength: 0.6201243426185101
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
